#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 65;
long red = 0;
long green = 0;
long blue = 0;

bool isGreen() {
	return ((green-red) > 20 && (green-blue) > 20);
}
bool isBlue() {
	return ((blue-red)>20 && (blue-green)>20);
}
bool isRed() {
	return ((red-green)>20 && (red-blue)>20);
}

void checkColor(){
	getColorRGB(colorSensor, red, green, blue);
	displayTextLine(2, "R%d G%d B%d", red, green, blue);
	displayTextLine(3, "L%d", getColorReflected(colorSensor));
}

void initialMove(){
  setMotor(leftMotor, 80);
  setMotor(rightMotor, 100);
  sleep (500);
}

void moveABit(){
	setMotor(leftMotor, 100);
  setMotor(rightMotor,100);
  sleep (200);
}

void followUntil(){
	while(!isGreen()&&!isRed())
  {
  	// sensor sees light:
    if(getColorReflected(colorSensor) < threshold)
    {
      // steer left
      motor[leftMotor]  = 100;
      motor[rightMotor] = 0;
    }
    // sensor sees dark:
    else
    {
      // steer right
      motor[leftMotor]  = 0;
      motor[rightMotor] = 100;
    }
    checkColor();
  }
}

void putarKiri(int derajat) {
	displayTextLine(4,"kiri");
	int initialGyro = getGyroHeading(gyroSensor);
	stopAllMotors();
	setMotor(leftMotor, -25);
	setMotor(rightMotor, 25);
	while (getGyroHeading(gyroSensor) - initialGyro > -derajat) {
		sleep(1);
	}
	stopAllMotors();
	resetGyro(gyroSensor);
}

void putarKanan(int derajat) {
	displayTextLine(4,"kanan");
	int initialGyro = getGyroHeading(gyroSensor);
	stopAllMotors();
	setMotor(leftMotor, 25);
	setMotor(rightMotor, -25);
	while (getGyroHeading(gyroSensor) - initialGyro < derajat) {
		sleep(1);
	}
	stopAllMotors();
	resetGyro(gyroSensor);
}

task main()
{
  initialMove();
  while(!isBlue()){
  	followUntil();
  	checkColor();
  	if(isGreen()){
  		moveABit();
  		putarKanan(90);
  	}
  	else if (isRed()){
  		putarKanan(180);
  	}
		checkColor();
  }
}
